### PR TITLE
Ported to 1.19.4

### PR DESCRIPTION
**Pull request by gisellevonbingen**

### CODE REVIEW

**Comment by Minenash** [comment]
Before I merge it, I assume this has been tested?

Also, what's the reason behind the major version being bumped?

**Comment by gisellevonbingen** [comment]
Yes i tested.
Bump version doesn't mean much.
just for avoid same file name.

**Comment by Estecka** [comment]
I wasn't able to get this working on the Fabric client: the `ClientBuiltinResourcePackProviderMixin` is trying to inject into a method `register` which does not exist.

**Comment by Minenash** [comment]
Closed in favor of #6

**Pull request closed without merging**
